packages:
  - packages/*
  - apps/*

linkWorkspacePackages: true
packageImportMethod: "clone-or-copy"
cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild
  - nx
  - sharp
  - unrs-resolver
